from __future__ import annotations

from pathlib import Path

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle


ROOT = Path(__file__).resolve().parents[2]


def p(text: str, style: ParagraphStyle) -> Paragraph:
    return Paragraph(text.replace("&", "&amp;"), style)


def main() -> None:
    out = ROOT / "brief.pdf"
    doc = SimpleDocTemplate(str(out), pagesize=letter, rightMargin=0.45 * inch, leftMargin=0.45 * inch, topMargin=0.4 * inch, bottomMargin=0.4 * inch)
    styles = getSampleStyleSheet()
    styles["Title"].fontSize = 16
    styles["Heading2"].fontSize = 11
    styles["Heading2"].spaceBefore = 7
    styles["Heading2"].spaceAfter = 3
    styles["BodyText"].fontSize = 8.5
    styles["BodyText"].leading = 10.2
    small = ParagraphStyle("Small", parent=styles["BodyText"], fontSize=7.4, leading=8.8)

    story = [
        p("NutriAI Technical Brief", styles["Title"]),
        p("<b>Student:</b> Arshnoor Bhatia | <b>Course:</b> BAX-423 Big Data, Spring 2026", styles["BodyText"]),
        p("<b>Deployment URL:</b> TODO add Streamlit Cloud URL | <b>GitHub:</b> TODO add repository URL", styles["BodyText"]),
        Spacer(1, 5),
        p("1. System Overview", styles["Heading2"]),
        p(
            "NutriAI is a Streamlit application that generates a personalized meal planner for students and shared households with clinical, allergy, diet, budget, and meal-prep constraints. The app starts with an empty household so users can add or remove people themselves, then supports a 1-4 week look-ahead horizon. The first 7 days remain the required no-repeat rubric plan. Workflow: Household intake -> filter aggregation -> validation -> clinical/allergy hard filters -> candidate generation -> Bloom precheck -> embedding-aware ranking -> diversity assignment -> visual week/day planner -> macro/micro charts -> grocery export + restaurant mode. Clinical restrictions and allergens are hard filters; swaps only use meals that have passed the safety screen.",
            styles["BodyText"],
        ),
        p("2. Data Pipeline", styles["Heading2"]),
        p(
            "The offline food snapshot is generated by code/scripts/build_food_snapshot.py from official USDA FoodData Central CSV archives: Foundation Foods April 2026, SR Legacy April 2018, and Survey/FNDDS October 2024. The pipeline downloads ZIP archives, extracts food and nutrient tables, maps FDC nutrient IDs plus FNDDS legacy nutrient numbers, pivots nutrients into structured records, deduplicates normalized descriptions, and adds keyword metadata for allergens and clinical caution flags. Final snapshot: 12,000 USDA-derived records in data/food_snapshot.csv.",
            styles["BodyText"],
        ),
        p(
            "The planner uses data/recipe_catalog.csv, a curated catalog of 99 recipe candidates with complete macro/micronutrients, clinical flags, diet compatibility, allergens, cross-contact risks, GI estimates, sodium, potassium, and grocery fields. This keeps the nutrition pipeline real while making recommendations safe and demoable.",
            styles["BodyText"],
        ),
        p("3. Core Capabilities", styles["Heading2"]),
    ]

    core_rows = [
        ["Capability", "Implementation"],
        ["Clinical filtering", "IBS, GERD, Type 2 Diabetes, and Hypertension rules using low-FODMAP, trigger, GI, sodium, and DASH constraints."],
        ["Allergy exclusion", "Direct allergens and strict cross-contact risks are removed before ranking."],
        ["Diet handling", "Vegan, vegetarian, pescatarian, non-vegetarian, mixed meal diets, no pork, no beef, and halal-style constraints."],
        ["Diversity", "No repeated recipes; category diversity score is reported."],
        ["Nutrition", "Per-meal and daily totals for macros plus iron, calcium, B12, vitamin D, zinc, sodium, potassium, magnesium."],
        ["Sub-60 sec", "Generation time is logged and displayed."],
    ]
    table = Table(core_rows, colWidths=[1.25 * inch, 6.0 * inch])
    table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#E8F3EF")),
                ("GRID", (0, 0), (-1, -1), 0.25, colors.grey),
                ("FONTSIZE", (0, 0), (-1, -1), 7.2),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ]
        )
    )
    story.extend([table, Spacer(1, 4), p("4. BAX-423 Techniques and Benchmarks", styles["Heading2"])])

    bench_rows = [
        ["Technique", "Benchmark Result", "Impact"],
        ["Bloom-filter screening", "Exact token scan 2305.35 ms vs Bloom precheck 1710.98 ms", "1.35x faster on expanded catalog before exact verification."],
        ["Hash embeddings + ranking", "Calorie-only baseline: 0 persona-specific flags, diversity 0.82. Optimized: 0 flags, diversity 0.93.", "Improved diversity while preserving hard-filter safety."],
        ["Sub-60 generation", "Mean 0.092s, max 0.108s across required personas", "All plans generated far below the 60s cap."],
    ]
    bench = Table(bench_rows, colWidths=[1.55 * inch, 3.55 * inch, 2.15 * inch])
    bench.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#F4EFE3")),
                ("GRID", (0, 0), (-1, -1), 0.25, colors.grey),
                ("FONTSIZE", (0, 0), (-1, -1), 7.0),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ]
        )
    )
    story.extend([bench, Spacer(1, 4), p("5. Required Persona Test Results", styles["Heading2"])])

    persona_rows = [
        ["Persona", "Required Criteria", "Result"],
        ["Priya", "IBS-safe, vegetarian, dairy/lactose-free, iron >= 80% RDA daily", "Pass"],
        ["Ravi", "GERD-safe, gluten-free, no pork, diversity >= 0.7, B12 >= 80% RDA daily", "Pass"],
        ["Mei", "Vegan, tree-nut-free, all meals GI <= 55, fiber >= 25g/day", "Pass"],
        ["James", "Pescatarian, soy-free, sodium <= 1500mg/day, >=3 fish meals, potassium >=80% RDA", "Pass"],
    ]
    personas = Table(persona_rows, colWidths=[0.8 * inch, 5.5 * inch, 0.8 * inch])
    personas.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#EAEFF7")),
                ("GRID", (0, 0), (-1, -1), 0.25, colors.grey),
                ("FONTSIZE", (0, 0), (-1, -1), 7.2),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ]
        )
    )
    story.extend(
        [
            personas,
            Spacer(1, 4),
            p("All four personas also passed clinical filtering, allergy exclusion, diet handling, diversity, nutrient analytics, and sub-60-second generation. Full table: docs/persona_test_results.csv.", small),
            p("6. Student Extensions", styles["Heading2"]),
            p(
                "<b>Household Planner Mode:</b> Displays the generated plan in polished week and day views, supports multiple household members, color-codes allergy chips, and lets users safely swap or replace meals. <b>Visual Design:</b> Uses a restrained light green dashboard theme with compact cards, metrics, and charts. <b>Nutrition Charts:</b> Adds a macro split donut chart and selectable daily trend chart. <b>Grocery List Mode:</b> Aggregates planned meals, tracks reuse frequency, scales cost estimates by household size, and exports to CSV. <b>Restaurant Mode:</b> Applies the same filters to a student restaurant snapshot and labels items as safer pick, caution, or avoid.",
                styles["BodyText"],
            ),
            p("7. Limitations and Next Steps", styles["Heading2"]),
            p(
                "The app is a class project, not medical advice. GI values, clinical flags, and restaurant allergen confidence are estimated from curated metadata. Restaurant Mode should be validated against official restaurant allergen PDFs or live APIs before real-world use. Future work would add real restaurant API ingestion, barcode scanning, a larger recipe database, adaptive feedback learning, and dietitian-reviewed clinical rules.",
                styles["BodyText"],
            ),
        ]
    )
    doc.build(story)
    print(f"Wrote {out}")


if __name__ == "__main__":
    main()
